package com.clementscode.mmi.swing;

public interface MediatorListenerCustomer {
	public enum Action {
		OPEN, QUIT, DEBUG, SAVE_AS, SAVE, ATTENDING, INDEPENDENT, VERBAL, MODELING, NO_ANSWER, WRONG_ANSWER, TOGGLE_BUTTONS, TIMER, BETWEEN_TIMER, CHANGE_DELAY_TIMER, SHOW_LOGGING_FRAME, BASELINE_MODE
	};

}
